-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS exam_pm11.clients
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT email UNIQUE (email)
);

COMMENT ON TABLE exam_pm11.clients
    IS 'Table of internet shop clients';

COMMENT ON COLUMN exam_pm11.clients.id
    IS 'Primary key, auto-increment';

COMMENT ON COLUMN exam_pm11.clients.name
    IS 'Client''s full name (last name and initials)';

COMMENT ON COLUMN exam_pm11.clients.email
    IS 'Client''s email address, unique';

COMMENT ON COLUMN exam_pm11.clients.city
    IS 'Client''s city of residence';

CREATE TABLE IF NOT EXISTS exam_pm11.categories
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE exam_pm11.categories
    IS 'Tables of product''s categories';

COMMENT ON COLUMN exam_pm11.categories.id
    IS 'Primary key, auto-increment';

COMMENT ON COLUMN exam_pm11.categories.name
    IS 'Product''s categories name';

CREATE TABLE IF NOT EXISTS exam_pm11.managers
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE exam_pm11.managers
    IS 'Table of shop''s managers';

COMMENT ON COLUMN exam_pm11.managers.id
    IS 'Primary key, auto-increment';

COMMENT ON COLUMN exam_pm11.managers.name
    IS 'Manager''s full name (last name and initials)';

COMMENT ON COLUMN exam_pm11.managers.phone
    IS 'Manager''s phone';

CREATE TABLE IF NOT EXISTS exam_pm11.products
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    title character varying(255) NOT NULL,
    category_id bigint NOT NULL,
    price numeric(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE exam_pm11.products
    IS 'Table of internet shop products';

COMMENT ON COLUMN exam_pm11.products.id
    IS 'Primary key, auto-increment';

COMMENT ON COLUMN exam_pm11.products.title
    IS 'Products''s name';

COMMENT ON COLUMN exam_pm11.products.category_id
    IS 'Foreign key referencing the categories table';

COMMENT ON COLUMN exam_pm11.products.price
    IS 'Products''s price';

CREATE TABLE IF NOT EXISTS exam_pm11.orders
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    date date NOT NULL,
    client_id bigint NOT NULL,
    product_id bigint NOT NULL,
    manager_id bigint NOT NULL,
    amount integer NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE exam_pm11.orders
    IS 'Table of internet shop orders';

COMMENT ON COLUMN exam_pm11.orders.id
    IS 'Primary key, auto-increment';

COMMENT ON COLUMN exam_pm11.orders.date
    IS 'Order''s date';

COMMENT ON COLUMN exam_pm11.orders.client_id
    IS 'Foreign key referencing the clients table';

COMMENT ON COLUMN exam_pm11.orders.product_id
    IS 'Foreign key referencing the products table';

COMMENT ON COLUMN exam_pm11.orders.manager_id
    IS 'Foreign key referencing the managers table';

COMMENT ON COLUMN exam_pm11.orders.amount
    IS 'Product''s amount in order';

ALTER TABLE IF EXISTS exam_pm11.products
    ADD CONSTRAINT category FOREIGN KEY (category_id)
    REFERENCES exam_pm11.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exam_pm11.orders
    ADD CONSTRAINT client FOREIGN KEY (client_id)
    REFERENCES exam_pm11.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exam_pm11.orders
    ADD CONSTRAINT product FOREIGN KEY (product_id)
    REFERENCES exam_pm11.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS exam_pm11.orders
    ADD CONSTRAINT manager FOREIGN KEY (manager_id)
    REFERENCES exam_pm11.managers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;